version: '3.8'

services:
  # Rails Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
      - sidekiq
    environment:
      RAILS_ENV: production
      DATABASE_URL: "mysql2://root:123456@db/chat_system_DB"
      REDIS_URL: "redis://redis:6379/1"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      SECRET_KEY_BASE: "your_secret_key_base"

  # MySQL Database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # Redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6378:6379"

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  # Sidekiq Jobs
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - ".:/rails"
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: "redis://redis:6379/1"
      DATABASE_URL: "mysql2://root:123456@db/chat_system_DB"

  # Whenever Cron Job
  cron:
    image: ruby:3.0.6
    command: ["whenever", "update-crontab"]
    volumes:
      - ".:/rails"
    depends_on:
      - web
    entrypoint: ["/bin/sh", "-c", "bundle exec whenever --update-crontab"]

volumes:
  mysql_data:
