version: '3.8'

services:
  # Rails Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: >
      bash -c "
        /usr/local/bin/wait-for-it -t 0 db:3306 &&
        ./bin/rails db:create && ./bin/rails db:migrate &&
        ./bin/rails server
      "
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
      - sidekiq
    environment:
      RAILS_ENV: production
      DATABASE_URL: "mysql2://root:root_password@db/chat_system_DB"
      REDIS_URL: "redis://redis:6379/1"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      SECRET_KEY_BASE: "a2ed125a50ca8daafd1ebdb6c5edccef8d5438512fcaa4fb77cc5c890e4ac7cb99aa8f9702f5d8b87f553caf3b10d67f0312c1e04909cc85c9c5348a029b6338"

  # MySQL Database
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chat_system_DB
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # Redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6378:6379"

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  # Sidekiq Jobs
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidekiq
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - ".:/rails"
    depends_on:
      - redis
      - db
      - elasticsearch
    environment:
      REDIS_URL: "redis://redis:6379/1"
      DATABASE_URL: "mysql2://root:root_password@db/chat_system_DB"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

  # Whenever Cron Job
  cron:
    image: ruby:3.0.6
    container_name: cron
    command: ["whenever", "update-crontab"]
    volumes:
      - ".:/rails"
    depends_on:
      - web
    entrypoint: ["/bin/sh", "-c", "bundle exec whenever --update-crontab"]

volumes:
  mysql_data:
