default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root_password
  host: db
  database: chat_system_DB
  port: 3306

development:
  <<: *default

test:
  <<: *default
  database: chat_system_test

production:
  <<: *default
